#!/usr/bin/env bash
#
# Generate a docker-compose overlay declaring N writer replicas with
# explicit REPLICA_INDEX, then bring up the stack.
#
# Why a generator: docker compose --scale gives every replica HOSTNAME
# = container_id (12-char hex) instead of <service>-<N>, so the
# writer's HOSTNAME-suffix fallback can't derive shard indices. The
# only portable way to run N>1 writers with per-scan affinity in
# vanilla docker compose is N explicit services. This script writes
# them deterministically.
#
# Usage:
#   ./scripts/sharded-compose.sh up <N>      # render & start
#   ./scripts/sharded-compose.sh down        # tear down
#   ./scripts/sharded-compose.sh render <N>  # write overlay, don't start
#
# Generated file path (gitignored): docker-compose.sharded.gen.yml

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
cd "$REPO_DIR"

OVERLAY="docker-compose.sharded.gen.yml"
ACTION="${1:-}"

render() {
    local n="$1"
    if [[ ! "$n" =~ ^[0-9]+$ ]] || [[ "$n" -lt 1 ]]; then
        echo "N must be a positive integer (got: $n)" >&2
        exit 1
    fi
    {
        echo "# AUTO-GENERATED by scripts/sharded-compose.sh — do not hand-edit."
        echo "# Declares ${n} writer replicas with explicit REPLICA_INDEX so the"
        echo "# writer durable consumers bind to one shard each. Regenerate by"
        echo "# running 'scripts/sharded-compose.sh render ${n}'."
        echo
        echo "services:"
        echo "  scanner:"
        echo "    environment:"
        echo "      HARPORIS_FINDINGS_SHARDS: \"${n}\""
        echo
        echo "  writer:"
        echo "    deploy:"
        echo "      replicas: 0"
        echo
        for ((i = 0; i < n; i++)); do
            echo "  writer-${i}:"
            echo "    extends:"
            echo "      file: docker-compose.yml"
            echo "      service: writer"
            echo "    container_name: harporis-writer-${i}"
            echo "    environment:"
            echo "      NATS_URL: nats://nats:4222"
            echo "      NATS_TOKEN: \"\${NATS_TOKEN:-harporis-dev}\""
            echo "      LOG_LEVEL: info"
            echo "      HARPORIS_FINDINGS_SHARDS: \"${n}\""
            echo "      HARPORIS_REPLICA_INDEX: \"${i}\""
            echo
        done
    } >"$OVERLAY"
    echo "wrote $OVERLAY ($n writer shards)"
}

case "$ACTION" in
    render)
        render "${2:-}"
        ;;
    up)
        render "${2:-}"
        docker compose -f docker-compose.yml -f "$OVERLAY" up -d --build
        ;;
    down)
        if [[ -f "$OVERLAY" ]]; then
            docker compose -f docker-compose.yml -f "$OVERLAY" down
        else
            docker compose down
        fi
        ;;
    *)
        cat <<EOF
usage:
  $0 up <N>       generate overlay for N writer shards and start the stack
  $0 render <N>   generate overlay only
  $0 down         tear down the sharded stack (or plain compose if no overlay)
EOF
        exit 1
        ;;
esac
